const PLACEHOLDER = "https://ui-avatars.com/api/?name=MA&background=0F172A&color=3B82F6&size=512&bold=true";

export const PLAYERS_DATA = [
    // --- GOALKEEPERS (25) ---
    {"name": "Emiliano Martinez", "position": "GK", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/St._Louis_City_vs_Aston_Villa_%28Jul_2025%29_14_%28Emiliano_Mart%C3%ADnez%29.jpg/500px-St._Louis_City_vs_Aston_Villa_%28Jul_2025%29_14_%28Emiliano_Mart%C3%ADnez%29.jpg"},
    {"name": "Manuel Neuer", "position": "GK", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/20180602_FIFA_Friendly_Match_Austria_vs._Germany_Manuel_Neuer_850_0723.jpg/500px-20180602_FIFA_Friendly_Match_Austria_vs._Germany_Manuel_Neuer_850_0723.jpg"},
    {"name": "Gigi Buffon", "position": "GK", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg/500px-Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg"},
    {"name": "Iker Casillas", "position": "GK", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Iker-Casillas-SportsTrade-2021-cropped.jpg/500px-Iker-Casillas-SportsTrade-2021-cropped.jpg"},
    {"name": "Lev Yashin", "position": "GK", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/LevYashin.JPG/500px-LevYashin.JPG"},
    {"name": "Alisson Becker", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Thibaut Courtois", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Jan Oblak", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Marc-Andre ter Stegen", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Ederson", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Mike Maignan", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "David Raya", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Gregor Kobel", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Unai Simon", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Jordan Pickford", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Andre Onana", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Guglielmo Vicario", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Yassine Bounou", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Dominik Livakovic", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Emi Martinez", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Nick Pope", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Bernd Leno", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Aaron Ramsdale", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Kepa Arrizabalaga", "position": "GK", "image_url": PLACEHOLDER},
    {"name": "Hugo Lloris", "position": "GK", "image_url": PLACEHOLDER},

    // --- DEFENDERS (55) ---
    {"name": "Paolo Maldini", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Sergio Ramos", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Virgil van Dijk", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Roberto Carlos", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Cafu", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "John Stones", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Ruben Dias", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Kyle Walker", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Achraf Hakimi", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Theo Hernandez", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Alphonso Davies", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Trent Alexander-Arnold", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Andrew Robertson", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "William Saliba", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Gabriel Magalhães", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Ronald Araujo", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Jules Kounde", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Antonio Rudiger", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Eder Militao", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Marquinhos", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Alessandro Bastoni", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Federico Dimarco", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Josko Gvardiol", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Min-jae Kim", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Dayot Upamecano", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Matthijs de Ligt", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Gleison Bremer", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Nuno Mendes", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Jeremie Frimpong", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Alejandro Grimaldo", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Cristian Romero", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Micky van de Ven", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Pau Torres", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Lisandro Martinez", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Sven Botman", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Ibrahima Konate", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Ben White", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Takehiro Tomiyasu", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Manuel Akanji", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Nathan Ake", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Kieran Trippier", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Reece James", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Ben Chilwell", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Luke Shaw", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Raphael Varane", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Harry Maguire", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Carles Puyol", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Gerard Pique", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Dani Alves", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Philipp Lahm", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Fabio Cannavaro", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Rio Ferdinand", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Nemanja Vidic", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "John Terry", "position": "DEF", "image_url": PLACEHOLDER},
    {"name": "Vincent Kompany", "position": "DEF", "image_url": PLACEHOLDER},

    // --- MIDFIELDERS (55) ---
    {"name": "Zinedine Zidane", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Luka Modric", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Kevin De Bruyne", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Andres Iniesta", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Xavi Hernandez", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Rodri", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Jude Bellingham", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Declan Rice", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Martin Odegaard", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Bernardo Silva", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Bruno Fernandes", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Jamal Musiala", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Florian Wirtz", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Federico Valverde", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Eduardo Camavinga", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Aurelien Tchouameni", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Pedri", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Gavi", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Frenkie de Jong", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Ilkay Gundogan", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Joshua Kimmich", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Leon Goretzka", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Alexis Mac Allister", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Enzo Fernandez", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Moises Caicedo", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Dominik Szoboszlai", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Nicolo Barella", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Hakan Calhanoglu", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Teun Koopmeiners", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Warren Zaire-Emery", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Douglas Luiz", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Bruno Guimaraes", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Lucas Paqueta", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "James Maddison", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Conor Gallagher", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Kobbie Mainoo", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Adam Wharton", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Joao Neves", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Vitinha", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Ruben Neves", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Sergej Milinkovic-Savic", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Andrea Pirlo", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Steven Gerrard", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Frank Lampard", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Paul Scholes", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Patrick Vieira", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Claude Makelele", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Kaka", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Mesut Ozil", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Cesc Fabregas", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "David Silva", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Toni Kroos", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Casemiro", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Fernandinho", "position": "MID", "image_url": PLACEHOLDER},
    {"name": "Sergio Busquets", "position": "MID", "image_url": PLACEHOLDER},

    // --- FORWARDS (56) ---
    {"name": "Lionel Messi", "position": "FWD", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178.jpg/500px-Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178.jpg"},
    {"name": "Cristiano Ronaldo", "position": "FWD", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Cristiano_Ronaldo_2275_%28cropped%29.jpg/500px-Cristiano_Ronaldo_2275_%28cropped%29.jpg"},
    {"name": "Kylian Mbappe", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Erling Haaland", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Neymar Jr", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Vinicius Jr", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Mohamed Salah", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Harry Kane", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Robert Lewandowski", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Antoine Griezmann", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Bukayo Saka", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Phil Foden", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Lamine Yamal", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Rodrygo Goes", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Lautaro Martinez", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Victor Osimhen", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Rafael Leao", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Khvicha Kvaratskhelia", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Son Heung-min", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Luis Diaz", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Darwin Nunez", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Julian Alvarez", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Gabriel Martinelli", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Gabriel Jesus", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Kai Havertz", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Alexander Isak", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Ollie Watkins", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Cole Palmer", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Anthony Gordon", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Jarrod Bowen", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Moussa Diaby", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Nicolas Jackson", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Christopher Nkunku", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Rasmus Hojlund", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Marcus Rashford", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Alejandro Garnacho", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Dusan Vlahovic", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Federico Chiesa", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Alvaro Morata", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Nico Williams", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Takefusa Kubo", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Leroy Sane", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Kingsley Coman", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Serge Gnabry", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Victor Boniface", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Loïs Openda", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Benjamin Sesko", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Santiago Gimenez", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Ronaldinho", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Ronaldo Nazario", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Thierry Henry", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Wayne Rooney", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Sergio Aguero", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Luis Suarez", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Zlatan Ibrahimovic", "position": "FWD", "image_url": PLACEHOLDER},
    {"name": "Karim Benzema", "position": "FWD", "image_url": PLACEHOLDER}
];
